# Performance difference between NumPy array and Python list

In [1]:
# numpy performance based on time
import numpy as np
myarr = np.arange(100000)    # the function is 'arange' similar to python built-in 'range'
# ex1 = np.arange(5)
# ex2 = np.arange(5)
# ex3 = ex1 + ex2        # what numpy does is that it performs arithmetic operations on the elements
# print(ex3)             # of array when multiplied, unlike a list which extends
%time for _ in range(10): myarr2 = myarr * 2 
print(myarr2.shape)  # array_name.shape  : tells you the shape (size) of the array
print(myarr2.dtype)  # array_name.dtype  : gives you the datatype of the homogeneous data

Wall time: 995 µs
(100000,)
int32


In [2]:
# python list performance for the same using a list

mylis = list(range(100000))

%time for _ in range(10): mylis2 = [x * 2 for x in mylis] # nested loop

Wall time: 81.8 ms


# ndarrays
* To create an array use the array function (similar to list(), tuple() or dict())
* You can convert any sequence like object to an array, such as a list
* you can also include arrays in an array

In [3]:
# for example you can convert the following list into an array using the array function

data = [1, 4, 6, 6, 3]

darr = np.array(data, dtype= 'int32') # data type for an array is automatically defined as per data
darr   # you can explicity define data type using 'dtype' while creating an array

array([1, 4, 6, 6, 3])

# ndarrays can also convert nested lists into multi-dimensional arrays 

In [4]:
# nested list or lists within a list 

nesdata = [[2, 5, 7, 2], [3, 9, 2, 4]]

nesarr = np.array(nesdata)
print(nesarr)
print(nesarr.shape) # (2, 4) where 2 is the number of arrays and 4 is the number of elements in arrays
print(nesarr.dtype)

# you can create 3-D (three dimensional) arrays using 3 parameters

threearr = np.zeros((3, 2, 4), dtype = 'int32')
threearr[0] = [[1, 3, 4, 5]]
threearr[1] = [2, 1, 1, 2]
threearr[2][1] = threearr[0][0] + threearr[1, 0] # [1][0] is same as [1, 0]
threearr[2][0] = threearr[0][0] * threearr[1][0]
# print(threearr)

onarr = np.ones((2, 4), dtype = 'int32', order = 'F')
print(onarr)
# thus instead of threearr[2][0][2:] to slice we can use threearr[2, 0, 2:]
cop = threearr[2, 0, 2:].copy()  # array_name.copy() is used to copy the sliced portion of array
print(cop)    # if copy() is not used, any changes made to the slice, will change the array
cop.shape

[[2 5 7 2]
 [3 9 2 4]]
(2, 4)
int32
[[1 1 1 1]
 [1 1 1 1]]
[ 4 10]


(2,)

In [5]:
# array slicing 

arr3 = np.array([[1, 3, 5], [3, 5, 6], [4, 7, 9]])
print(arr3)
print('-------------------')
print(arr3[1:2, :2])
print('-------------------')
print(arr3[:, :2])

[[1 3 5]
 [3 5 6]
 [4 7 9]]
-------------------
[[3 5]]
-------------------
[[1 3]
 [3 5]
 [4 7]]


In [6]:
import math
a = np.arange(4, 7).reshape((3, 1))
b = np.arange(1, 4).reshape((1, 3))
c = np.dot(a, b)
ra = np.random.randn(6, 3)
print(ra)
print('\n', ra.T)
np.dot(ra.T, ra)

[[ 0.14020703  0.34080298  0.84384362]
 [-1.99157448 -0.22136    -1.09676056]
 [-0.13614218  1.63250285 -0.22568595]
 [ 0.06013242 -0.77871335 -0.29592863]
 [ 0.1075587   1.27116135 -0.4509616 ]
 [-0.12957476  0.8819711   1.79440081]]

 [[ 0.14020703 -1.99157448 -0.13614218  0.06013242  0.1075587  -0.12957476]
 [ 0.34080298 -0.22136     1.63250285 -0.77871335  1.27116135  0.8819711 ]
 [ 0.84384362 -1.09676056 -0.22568595 -0.29592863 -0.4509616   1.79440081]]


array([[4.036536  , 0.24200275, 2.03450972],
       [0.24200275, 5.83033113, 1.40173865],
       [2.03450972, 1.40173865, 5.4767043 ]])

In [43]:
ex1 = np.arange(10)
ex11 = np.copy(ex1)
print(np.where(ex1 % 2 != 0, -1, ex1))
ex11.reshape((2, -1))   # -1 automatically decides the number of columns

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [79]:
a5 = np.linspace(1 ,4, 4)
a4 = np.arange(36).reshape((6, 6))
# print(a4)
import re
text=r'''Everyone has the following fundamental freedoms:
(a) freedom of conscience and religion;
(b) freedom of thought, belief, opinion and expression, including freedom of the press and other media of communication;
(c) freedom of peaceful assembly; and
(d) freedom of association.
'''
re.findall('(.)', text)

['E',
 'v',
 'e',
 'r',
 'y',
 'o',
 'n',
 'e',
 ' ',
 'h',
 'a',
 's',
 ' ',
 't',
 'h',
 'e',
 ' ',
 'f',
 'o',
 'l',
 'l',
 'o',
 'w',
 'i',
 'n',
 'g',
 ' ',
 'f',
 'u',
 'n',
 'd',
 'a',
 'm',
 'e',
 'n',
 't',
 'a',
 'l',
 ' ',
 'f',
 'r',
 'e',
 'e',
 'd',
 'o',
 'm',
 's',
 ':',
 '(',
 'a',
 ')',
 ' ',
 'f',
 'r',
 'e',
 'e',
 'd',
 'o',
 'm',
 ' ',
 'o',
 'f',
 ' ',
 'c',
 'o',
 'n',
 's',
 'c',
 'i',
 'e',
 'n',
 'c',
 'e',
 ' ',
 'a',
 'n',
 'd',
 ' ',
 'r',
 'e',
 'l',
 'i',
 'g',
 'i',
 'o',
 'n',
 ';',
 '(',
 'b',
 ')',
 ' ',
 'f',
 'r',
 'e',
 'e',
 'd',
 'o',
 'm',
 ' ',
 'o',
 'f',
 ' ',
 't',
 'h',
 'o',
 'u',
 'g',
 'h',
 't',
 ',',
 ' ',
 'b',
 'e',
 'l',
 'i',
 'e',
 'f',
 ',',
 ' ',
 'o',
 'p',
 'i',
 'n',
 'i',
 'o',
 'n',
 ' ',
 'a',
 'n',
 'd',
 ' ',
 'e',
 'x',
 'p',
 'r',
 'e',
 's',
 's',
 'i',
 'o',
 'n',
 ',',
 ' ',
 'i',
 'n',
 'c',
 'l',
 'u',
 'd',
 'i',
 'n',
 'g',
 ' ',
 'f',
 'r',
 'e',
 'e',
 'd',
 'o',
 'm',
 ' ',
 'o',
 'f',
 ' ',
 't',
 'h',
 'e'